spring:
  profiles:
    active: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: nft@nulink.org
      password: nft888@nulink.org
  application:
    name: nulink-living-ratio

telegram:
  bot:
    token: 6701412119:AAGdUGaXyXVb5Eup188o7dwPVNl8gr52e70
    chatId: -623331217
