controller:
  enabled: true
scheduling:
  enabled: true

server:
  port: 8091
spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/nulink_living_ratio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: XCarHikariCP
      max-lifetime: 28770000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      transaction:
        rollback-on-commit-failure: true

  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 60000
  redis:
    port: 6379
    host: 127.0.0.1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

contracts:
  start: 36115237
  step: 500
  enabled: true
  contractList:
    -
      name: 'StakingManager'
      address: '0x48A126A769bCb3d6aBa4B0C4E127a45075a37511'
      enabled: true
    -
      name: 'NuLinkStakingPool'
      address: '0xA3C0323E421cC64e64d5eF50e2C5587A6461Be53'
      enabled: true
    -
      name: 'NuLinkStakingSetting'
      address: '0x13cd891De2c924e2DFa08533Af2FF83bEd5B0077'
      enabled: true
    -
      name: 'NLKFaucet'
      address: '0x4bB24Ab269B02FBe34BD8eae5B4b406F53E8FF44'
      enabled: true

web3j:
  client-address:
    official: https://data-seed-prebsc-1-s1.bnbchain.org:8545
    ankr: https://rpc.ankr.com/bsc_testnet_chapel/1efbffd5898c6a7f6c352cb46bbee1b70535f3f68a6f00594e123a5b30a99daf
    blockpi: https://bsc-testnet.blockpi.network/v1/rpc/f2599ba0b23571e5510fa6e3d34e6d99c64e04a4
  admin-client: true # to manage accounts, enable the admin client
  httpTimeoutSeconds: 35

NULink:
  porter-service-url: http://8.222.146.98:9165
  password: xxxxxx
  chainId: 97
